version: '3.8'

networks:
  app-network:

volumes:
  app-data:

services:
  webserver:
    image: nginx:stable-alpine
    container_name: mathx-webserver
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      app-network:

  backend:
    build:
      args: 
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
      context: .docker/php
    container_name: mathx-backend
    volumes:
      - ./:/var/www/html
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      app-network:

  pgsql:
    image: 'postgres:14'
    container_name: mathx-db
    ports:
        - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
        PGPASSWORD: '${DB_PASSWORD:-secret}'
        POSTGRES_DB: '${DB_DATABASE}'
        POSTGRES_USER: '${DB_USERNAME}'
        POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
        - app-data:/var/lib/postgresql/data
    networks:
        app-network:
